scrfd:
    onnx_file:     "../weights/scrfd_10g_bnkps_shape640x640.onnx"
    engine_file:   "../weights/scrfd_10g_bnkps_shape640x640.trt"
    BATCH_SIZE:    1
    INPUT_CHANNEL: 3
    IMAGE_WIDTH:   640
    IMAGE_HEIGHT:  640
    image_order:   "BCHW"
    channel_order: "BGR"
    obj_threshold: 0.5
    nms_threshold: 0.45
    img_mean:      [ 127.5, 127.5, 127.5 ]
    img_std:       [ 128.0, 128.0, 128.0 ]    
    detect_mask:   False
    mask_thresh:   0.5
    landmark_std:  1
    feature_steps: [8, 16, 32]
    anchor_sizes:  [[8, 16], [32, 64], [128, 256]]
    alpha:         1.0
    resize:        "keep_ratio"
